# Generated by Django 4.2.5 on 2023-10-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('post', models.TextField()),
                ('slug', models.SlugField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
