# Generated by Django 4.2.5 on 2023-10-12 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_category_alter_post_slug_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('username', models.CharField(help_text='Your username should only contain alphabets, numbers and underscores (-)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\d-]{5,}')])),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('display_picture', models.ImageField(null=True, upload_to='user-img')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Blog.writer'),
        ),
    ]
